// Generated by CoffeeScript 1.6.2
var AddCodeFile, DeleteCodeFile, chooseLang, editCodeFile, logout, newCodeFile, saveFile, showFileList, showLangList, syncCodeFile, toggleMenuPanel;

toggleMenuPanel = function() {
  $('.modal').removeClass('active');
  return toggle_slide();
};

showFileList = function() {
  var file, files, listHtml, _i, _len;

  files = CodeFile.all();
  listHtml = '';
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    listHtml += "<li> <a href=\"javascript:;\" onclick=\"editCodeFile('" + file.id + "')\">" + file.name + "<span class=\"chevron\"></span></a></li>";
  }
  $('#code-file-list').html(listHtml);
  toggleMenuPanel();
  $('.modal').removeClass('active');
  return $('#codeFileListModal').addClass('active');
};

newCodeFile = function() {
  $('#code-id').val(0);
  $('#code-title').val('click here to edit file name');
  $('#code-lang').val('javascript');
  codeMirror.setValue('');
  codeMirror.setOption('mode', 'javascript');
  $('.modal').removeClass('active');
  return toggleMenuPanel();
};

editCodeFile = function(id) {
  var file;

  file = CodeFile.find(id);
  $('#code-id').val(id);
  $('#code-title').val(file.name);
  $('#code-lang').val(file.lang);
  codeMirror.setValue(file.content);
  codeMirror.setOption('mode', file.lang);
  return $('.modal').removeClass('active');
};

showLangList = function() {
  toggleMenuPanel();
  $('.modal').removeClass('active');
  return $('#chooseLangModal').addClass('active');
};

chooseLang = function(lang) {
  codeMirror.setOption('mode', lang);
  $('#code-lang').val(lang);
  return $('.modal').removeClass('active');
};

syncCodeFile = function() {
  CodeFile.sync_all();
  return toggleMenuPanel();
};

saveFile = function() {
  var codes, fileId, lang, title;

  fileId = '' + $('#code-id').val();
  title = $('#code-title').val();
  if (title.length < 1) {
    alert('Please add a name for your code file :)');
    return;
  }
  codes = codeMirror.getValue();
  lang = $('#code-lang').val();
  return AddCodeFile(fileId, title, codes, lang);
};

AddCodeFile = function(id, name, content, lang) {
  var created, file, updated;

  updated = Math.round(new Date().getTime() / 1000);
  if (id === '0') {
    created = Math.round(new Date().getTime() / 1000);
    updated = created;
    file = CodeFile.create({
      'id': id,
      'created': created,
      'updated': updated,
      'name': name,
      'content': content,
      'lang': lang
    });
    id = file.id;
  } else {
    file = CodeFile.find(id);
    file.updated = updated;
    file.name = name;
    file.content = content;
    file.lang = lang;
    file.save();
  }
  CodeFile.sync_all();
  return $('#code-id').val(id);
};

DeleteCodeFile = function(id) {
  CodeFile.find(id).destroy();
  return CodeFile.sync_all();
};

logout = function() {
  window.localStorage.clear();
  toggleMenuPanel();
  return $('#loginModal').addClass('active');
};
