// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    new FastClick(document.body);
    return Nimbus.Auth.set_app_ready(function() {
      console.log("app ready called");
      if (Nimbus.Auth.authorized()) {
        return $("#loginModal").removeClass("active");
      }
    });
  });

}).call(this);
